---

- name: ensure mpd is installed
  package:
    name: "{{ mpd_packages }}"

- name: add user {{ mpd_user }} to groups
  user:
    name: "{{ mpd_user }}"
    groups: "{{ item }}"
    append: true
  loop:
    "{{ mpd_groups | sort | unique }}"

- name: support redhat based version 7
  block:
    - name: ensure mpd.service.d is present
      file:
        dest: /etc/systemd/system/mpd.service.d
        state: directory
        mode: 0750

    - name: create overwrite.conf for systemd
      template:
        src: systemd/overwrite.conf.j2
        dest: "/etc/systemd/system/mpd.service.d/override.conf"
        mode: 0440
      notify:
        - systemctl daemon-reload
        - restart mpd
  when:
    - ansible_os_family | lower == 'redhat'
    - ansible_distribution_version | int == 7

...
