---
# - name: user and group handling
#   when:
#     - mpd_user != "root"
#   block:
#     - name: create alertmanager group
#       ansible.builtin.group:
#         name: "{{ mpd_group }}"
#         state: present
#         system: true
#
#     - name: create alertmanager user
#       ansible.builtin.user:
#         name: "{{ mpd_user }}"
#         groups: "{{ mpd_group }}"
#         append: true
#         shell: /usr/sbin/nologin
#         # system: true
#         createhome: false
#         home: "{{ mpd_state_file | dirname }}"

- name: ensure mpd is installed
  ansible.builtin.package:
    name: "{{ mpd_packages }}"

- name: add user {{ mpd_user }} to groups
  ansible.builtin.user:
    name: "{{ mpd_user }}"
    groups: "{{ item }}"
    append: true
  loop:
    "{{ mpd_groups | sort | unique }}"
  when:
    - mpd_groups is defined
    - mpd_groups | count > 0

- name: ensure log directory is present
  ansible.builtin.file:
    dest: "{{ mpd_log_file | dirname }}"
    state: directory
    owner: "{{ mpd_user }}"
    group: "{{ mpd_group }}"
    mode: 0770

- name: ensure music directory is present
  ansible.builtin.file:
    dest: "{{ mpd_music_directory }}"
    state: directory
    owner: "{{ mpd_user }}"
    group: "{{ mpd_group }}"
    mode: 0755

...
