---

- name: systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
  when:
    - ansible_service_mgr | lower == "systemd"

- name: restart mpd
  ansible.builtin.service:
    name: mpd
    state: restarted
